### DEV
POST http://localhost:5001/xamarin-tracker/us-central1/app/api/upsert
Content-Type: application/json

{
  "customId": "firstId",
  "item": {
    "payment": "70 EUR",
    "totalTime": "10:02:20",
    "totalCost": "700 EUR"
  }
}

###

GET http://localhost:5001/xamarin-tracker/us-central1/app/api/read/firstId


### PRODUCTION
GET https://us-central1-xamarin-tracker.cloudfunctions.net/app/api/read/testProd

###
POST https://us-central1-xamarin-tracker.cloudfunctions.net/app/api/upsert
Content-Type: application/json

{
  "customId": "testProd",
  "time": "15:02:20"
}